language: java

sudo: false

install: "mvn -P ci install"
script: "mvn -P ci clean compile test"

os:
- linux
- osx

jdk:
- oraclejdk8
- oraclejdk10
- openjdk11
- openjdk-ea

matrix:
  exclude:
  - os: osx
    jdk: oraclejdk8
  - os: osx
    jdk: oraclejdk10
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: oraclejdk10

after_success:
- bash < (curl -s https://codecov.io/bash)
